project:
  type: website
  output-dir: docs

website:
  title: "DS4SJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu: 
          - contributing.qmd
          - team.qmd
          - acknowledgements.qmd
      - href: notes.qmd
        text: Notes
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: 
      - custom.css
    toc: true



